# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='is_alive',
            field=models.BooleanField(default=False, verbose_name='正在使用'),
        ),
    ]
