# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170724_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='cover',
            name='name',
            field=models.CharField(default='cover', max_length=100, verbose_name='封面名'),
        ),
    ]
