# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170724_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否评分最高'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url_big',
            field=models.URLField(default='', verbose_name='电影封面-大'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url_me',
            field=models.URLField(default='', verbose_name='电影封面-中'),
        ),
    ]
